apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2023-09-28T00:13:47Z"
    name: node-exporter-service
    namespace: monitoring
    resourceVersion: "2672"
    uid: f550eeb2-a712-4b78-8be8-c1b788eaedde
  spec:
    clusterIP: 10.43.29.65
    clusterIPs:
    - 10.43.29.65
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
    selector:
      app: node-exporter
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "3000"
      prometheus.io/scrape: "true"
    creationTimestamp: "2023-10-08T02:38:41Z"
    name: grafana
    namespace: monitoring
    resourceVersion: "387631"
    uid: 2a23f0b8-d962-4c66-9fc6-f7cd8122904a
  spec:
    clusterIP: 10.43.201.88
    clusterIPs:
    - 10.43.201.88
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 32000
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: grafana
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"node-exporter"},"name":"node-exporter","namespace":"monitoring"},"spec":{"ports":[{"name":"node-exporter","port":9100,"protocol":"TCP","targetPort":9100}],"selector":{"app":"node-exporter"},"sessionAffinity":"None","type":"ClusterIP"}}
    creationTimestamp: "2023-10-15T21:07:52Z"
    labels:
      app: node-exporter
    name: node-exporter
    namespace: monitoring
    resourceVersion: "764087"
    uid: dd99e304-ad0d-4e36-9110-b270fd1c04bd
  spec:
    clusterIP: 10.43.44.98
    clusterIPs:
    - 10.43.44.98
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: node-exporter
      port: 9100
      protocol: TCP
      targetPort: 9100
    selector:
      app: node-exporter
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "9090"
      prometheus.io/scrape: "true"
    creationTimestamp: "2023-12-07T02:25:12Z"
    name: prometheus-service
    namespace: monitoring
    resourceVersion: "3023311"
    uid: c3936bca-0083-4fa0-b941-26574751b190
  spec:
    clusterIP: 10.43.126.118
    clusterIPs:
    - 10.43.126.118
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30000
      port: 8080
      protocol: TCP
      targetPort: 9090
    selector:
      app: prometheus-server
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: loki
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2023-12-07T02:37:01Z"
    labels:
      app: loki
      app.kubernetes.io/managed-by: Helm
      chart: loki-2.16.0
      heritage: Helm
      release: loki
      variant: headless
    name: loki-headless
    namespace: monitoring
    resourceVersion: "3023914"
    uid: df29208f-812d-4746-adfb-63ae173c0616
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: http-metrics
    selector:
      app: loki
      release: loki
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: loki
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2023-12-07T02:37:01Z"
    labels:
      app: loki
      app.kubernetes.io/managed-by: Helm
      chart: loki-2.16.0
      heritage: Helm
      release: loki
    name: loki-memberlist
    namespace: monitoring
    resourceVersion: "3023915"
    uid: 65e329b0-5697-467c-b2f0-1a7615c82818
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 7946
      protocol: TCP
      targetPort: memberlist-port
    publishNotReadyAddresses: true
    selector:
      app: loki
      release: loki
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: loki
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2023-12-07T02:37:01Z"
    labels:
      app: loki
      app.kubernetes.io/managed-by: Helm
      chart: loki-2.16.0
      heritage: Helm
      release: loki
    name: loki
    namespace: monitoring
    resourceVersion: "3023917"
    uid: f468ebcd-e0f1-47c8-b91f-39717edb9f36
  spec:
    clusterIP: 10.43.207.194
    clusterIPs:
    - 10.43.207.194
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: http-metrics
    selector:
      app: loki
      release: loki
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
